# GitHub Sponsors + alt-funding visibility. The "Sponsor" button on the repo header
# lands here. Shield is donation-funded — no paid tier, no hosted offering, no enterprise
# license. Code contributions count as funding.
github: [stoney-eagle]
# Uncomment as those accounts are set up:
# open_collective: shield
# liberapay: shield
# ko_fi: stoney
# custom:
#   - https://nomercy.tv/donate
