// Hand-written API types — generated by `npm run types:gen` once the API is running.
// Mirrors the entities/controllers described in Shield Phase 1 spec/plan.

export type Severity = 'Low' | 'Medium' | 'High' | 'Critical'
export type Ecosystem = 'Npm' | 'Nuget' | 'Composer' | 'Gradle' | 'Os'
export type SourceType = 'GithubRepo' | 'LocalFolder' | 'LinuxHost'
export type FindingState = 'Open' | 'Acked' | 'Resolved' | 'Suppressed'
export type ChannelType = 'Discord' | 'Ntfy' | 'Smtp' | 'Inbox'
export type Feed = 'Osv' | 'Ghsa' | 'NpmRegistry' | 'DepsDev' | 'Socket' | 'TrivyDb'

export interface Me {
  id: string
  username: string
  role: 'Admin' | 'Viewer'
  singleUser: boolean
  oidcEnabled: boolean
}

export interface LoginRequest {
  username: string
  password: string
  totpCode?: string
}

export interface Source {
  id: number
  type: SourceType
  name: string
  configJson: string
  scanInterval: string
  lastScannedAt: string | null
  lastError: string | null
  enabled: boolean
  createdAt: string
  updatedAt: string
}

export interface SourceCreate {
  type: SourceType
  name: string
  configJson: string
  scanInterval?: string
  enabled?: boolean
}

export interface InventoryItem {
  id: number
  ecosystem: Ecosystem
  name: string
  version: string
  isDirect: boolean
  parentChain: string[]
}

export interface Advisory {
  id: string
  feed: Feed
  externalId: string
  ecosystem: Ecosystem
  packageName: string
  severity: Severity
  cvss: number | null
  summary: string
  references: string[]
  publishedAt: string
  modifiedAt: string
}

export interface Finding {
  id: string
  sourceId: number
  sourceName: string
  inventoryItemId: number
  advisoryRefId: string
  advisory: Advisory
  ecosystem: Ecosystem
  packageName: string
  packageVersion: string
  severity: Severity
  firstSeenAt: string
  lastSeenAt: string
  state: FindingState
  dedupKey: string
  notes: string | null
}

export interface FindingFilter {
  severity?: Severity
  sourceId?: number
  ecosystem?: Ecosystem
  state?: FindingState
  page?: number
  pageSize?: number
}

export interface PagedResult<T> {
  items: T[]
  total: number
  page: number
  pageSize: number
}

export interface AlertChannel {
  id: string
  type: ChannelType
  name: string
  minSeverity: Severity
  enabled: boolean
  configMasked: Record<string, string>
}

export interface ChannelCreate {
  type: ChannelType
  name: string
  minSeverity: Severity
  enabled: boolean
  configJson: string
}

export interface FeedStatus {
  feed: Feed
  lastSuccessAt: string | null
  lastError: string | null
  nextRunAt: string | null
}

export interface DashboardStats {
  countsBySeverity: Record<Severity, number>
  totalSources: number
  staleSources: number
  recentFindings: Finding[]
}

export interface Settings {
  singleUser: boolean
  oidcEnabled: boolean
  oidcIssuer: string | null
}
