// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shield.Data;

#nullable disable

namespace Shield.Data.Migrations.Shield
{
    partial class AddSecurityEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType").HasColumnType("TEXT");

                    b.Property<string>("ClaimValue").HasColumnType("TEXT");

                    b.Property<Guid>("RoleId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType").HasColumnType("TEXT");

                    b.Property<string>("ClaimValue").HasColumnType("TEXT");

                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                b =>
                {
                    b.Property<string>("LoginProvider").HasColumnType("TEXT");

                    b.Property<string>("ProviderKey").HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName").HasColumnType("TEXT");

                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                b =>
                {
                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.Property<Guid>("RoleId").HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>",
                b =>
                {
                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.Property<string>("LoginProvider").HasColumnType("TEXT");

                    b.Property<string>("Name").HasColumnType("TEXT");

                    b.Property<string>("Value").HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.AgentToken",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<Guid>("HostId").HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt").HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt").HasColumnType("TEXT");

                    b.Property<bool>("Revoked").HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("TokenHash");

                    b.ToTable("AgentTokens", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.AlertChannel",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<string>("ConfigJsonEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled").HasColumnType("INTEGER");

                    b.Property<int>("MinSeverity").HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AlertChannels", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.AlertEvent",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<Guid>("ChannelId").HasColumnType("TEXT");

                    b.Property<string>("Error").HasMaxLength(2000).HasColumnType("TEXT");

                    b.Property<Guid>("FindingId").HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt").HasColumnType("TEXT");

                    b.Property<int>("Status").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("FindingId", "SentAt");

                    b.ToTable("AlertEvents", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.ApiToken",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt").HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt").HasColumnType("TEXT");

                    b.Property<string>("LastUsedIp").HasMaxLength(64).HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt").HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdFilter")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash").IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiTokens", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.AppSetting",
                b =>
                {
                    b.Property<string>("Key").HasMaxLength(200).HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy").HasColumnType("TEXT");

                    b.Property<string>("ValueEncrypted").IsRequired().HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.AuditEntry",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId").HasColumnType("TEXT");

                    b.Property<DateTime>("At").HasColumnType("TEXT");

                    b.Property<string>("DetailsJson").HasColumnType("TEXT");

                    b.Property<string>("RemoteIp").HasMaxLength(64).HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At", "Action", "TargetType");

                    b.ToTable("AuditEntries", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.Finding",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<Guid>("AdvisoryRefId").HasColumnType("TEXT");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt").HasColumnType("TEXT");

                    b.Property<int>("InventoryItemId").HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt").HasColumnType("TEXT");

                    b.Property<string>("Notes").HasMaxLength(4000).HasColumnType("TEXT");

                    b.Property<int>("Severity").HasColumnType("INTEGER");

                    b.Property<int>("SourceId").HasColumnType("INTEGER");

                    b.Property<int>("State").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey").IsUnique();

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("SourceId");

                    b.HasIndex("State");

                    b.ToTable("Findings", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.GroupMembership",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt").HasColumnType("TEXT");

                    b.Property<int>("GroupId").HasColumnType("INTEGER");

                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "UserId").IsUnique();

                    b.ToTable("GroupMemberships", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.IntegrationToken",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId").HasMaxLength(200).HasColumnType("TEXT");

                    b.Property<string>("AccountLogin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt").HasColumnType("TEXT");

                    b.Property<string>("Extra").HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedUserId").HasColumnType("TEXT");

                    b.Property<int>("Provider").HasColumnType("INTEGER");

                    b.Property<string>("RefreshTokenEncrypted").HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "LinkedUserId");

                    b.HasIndex("Provider", "Subject");

                    b.ToTable("IntegrationTokens", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.IpReputation",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country").HasMaxLength(2).HasColumnType("TEXT");

                    b.Property<bool>("CurrentlyBanned").HasColumnType("INTEGER");

                    b.Property<int>("EventCount").HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt").HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBannedAt").HasColumnType("TEXT");

                    b.Property<string>("LastJail").HasMaxLength(100).HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt").HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUnbannedAt").HasColumnType("TEXT");

                    b.Property<string>("Notes").HasMaxLength(2000).HasColumnType("TEXT");

                    b.Property<int>("Score").HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ip").IsUnique();

                    b.HasIndex("CurrentlyBanned", "LastSeenAt");

                    b.ToTable("IpReputations", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.InventoryItem",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ecosystem").HasColumnType("INTEGER");

                    b.Property<bool>("IsDirect").HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentChain").IsRequired().HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId").HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Ecosystem", "Name", "Version");

                    b.ToTable("InventoryItems", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.InventorySnapshot",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<string>("ContentsSha")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount").HasColumnType("INTEGER");

                    b.Property<int>("SourceId").HasColumnType("INTEGER");

                    b.Property<DateTime>("TakenAt").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("InventorySnapshots", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.Invite",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt").HasColumnType("TEXT");

                    b.Property<Guid?>("AcceptedByUserId").HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy").HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt").HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSentAt").HasColumnType("TEXT");

                    b.Property<string>("PreBoundEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreBoundLogin")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreBoundProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreBoundSubjectId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResendCount").HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAt").HasColumnType("TEXT");

                    b.Property<Guid?>("RevokedBy").HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGroupIdsCsv")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token").IsUnique();

                    b.HasIndex("AcceptedAt", "RevokedAt", "ExpiresAt");

                    b.ToTable("Invites", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.Notification",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt").HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<int>("Kind").HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt").HasColumnType("TEXT");

                    b.Property<string>("RelatedId").HasMaxLength(200).HasColumnType("TEXT");

                    b.Property<string>("RelatedType").HasMaxLength(50).HasColumnType("TEXT");

                    b.Property<int>("Severity").HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "ReadAt", "CreatedAt");

                    b.ToTable("Notifications", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.PackageWatch",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt").HasColumnType("TEXT");

                    b.Property<int>("Ecosystem").HasColumnType("INTEGER");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Ecosystem", "PackageName").IsUnique();

                    b.ToTable("PackageWatches", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.PushSubscription",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDeliveredAt").HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent").HasMaxLength(500).HasColumnType("TEXT");

                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint").IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.SavedFilter",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryJson").IsRequired().HasColumnType("TEXT");

                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind", "CreatedAt");

                    b.ToTable("SavedFilters", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.ScanQueueEntry",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");

                    b.Property<DateTime>("EnqueuedAt").HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId").HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("CompletedAt", "StartedAt", "EnqueuedAt");

                    b.ToTable("ScanQueueEntries", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.SecurityEvent",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<DateTime>("At").HasColumnType("TEXT");

                    b.Property<string>("DetailsJson").HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host").HasMaxLength(200).HasColumnType("TEXT");

                    b.Property<string>("Jail").HasMaxLength(100).HasColumnType("TEXT");

                    b.Property<string>("Path").HasMaxLength(500).HasColumnType("TEXT");

                    b.Property<string>("RemoteIp").HasMaxLength(64).HasColumnType("TEXT");

                    b.Property<int>("Severity").HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent").HasMaxLength(500).HasColumnType("TEXT");

                    b.Property<string>("UserName").HasMaxLength(200).HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Host");

                    b.HasIndex("RemoteIp");

                    b.HasIndex("At", "Source", "Severity");

                    b.ToTable("SecurityEvents", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.Source",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson").IsRequired().HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<string>("DetectedRemote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled").HasColumnType("INTEGER");

                    b.Property<string>("LastError").HasMaxLength(2000).HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScannedAt").HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ScanInterval").HasColumnType("TEXT");

                    b.Property<int>("Type").HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sources", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.SourceAccess",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GrantedAt").HasColumnType("TEXT");

                    b.Property<Guid?>("GrantedBy").HasColumnType("TEXT");

                    b.Property<int?>("GroupId").HasColumnType("INTEGER");

                    b.Property<int>("Level").HasColumnType("INTEGER");

                    b.Property<int>("SourceId").HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "GroupId");

                    b.HasIndex("SourceId", "UserId");

                    b.ToTable("SourceAccesses", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.SourceGroup",
                b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SourceGroups", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.UserSession",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<DateTime>("LastActiveAt").HasColumnType("TEXT");

                    b.Property<string>("RemoteIp").HasMaxLength(64).HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt").HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("TEXT");

                    b.Property<Guid>("UserId").HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash").IsUnique();

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("UserSessions", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Data.Identity.ShieldRole",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name").HasMaxLength(256).HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                }
            );

            modelBuilder.Entity(
                "Shield.Data.Identity.ShieldUser",
                b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount").HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");

                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed").HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled").HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash").HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber").HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed").HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp").HasColumnType("TEXT");

                    b.Property<string>("TotpSecret").HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled").HasColumnType("INTEGER");

                    b.Property<string>("UserName").HasMaxLength(256).HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>",
                b =>
                {
                    b.HasOne("Shield.Data.Identity.ShieldRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>",
                b =>
                {
                    b.HasOne("Shield.Data.Identity.ShieldUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>",
                b =>
                {
                    b.HasOne("Shield.Data.Identity.ShieldUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>",
                b =>
                {
                    b.HasOne("Shield.Data.Identity.ShieldRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shield.Data.Identity.ShieldUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>",
                b =>
                {
                    b.HasOne("Shield.Data.Identity.ShieldUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.InventoryItem",
                b =>
                {
                    b.HasOne("Shield.Core.Domain.InventorySnapshot", "Snapshot")
                        .WithMany("Items")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.InventorySnapshot",
                b =>
                {
                    b.HasOne("Shield.Core.Domain.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                }
            );

            modelBuilder.Entity(
                "Shield.Core.Domain.InventorySnapshot",
                b =>
                {
                    b.Navigation("Items");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
