// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shield.Data;

#nullable disable

namespace Shield.Data.Migrations.Feeds
{
    [DbContext(typeof(FeedsDbContext))]
    [Migration("20260516200000_AddFeedSyncRateLimitResetAt")]
    partial class AddFeedSyncRateLimitResetAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Shield.Core.Domain.Advisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedRangesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cvss")
                        .HasColumnType("REAL");

                    b.Property<int>("Ecosystem")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EpssPercentile")
                        .HasColumnType("REAL");

                    b.Property<double?>("EpssScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Feed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKev")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("KevAddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("KevDueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ecosystem", "PackageName");

                    b.HasIndex("Feed", "ExternalId", "Ecosystem", "PackageName")
                        .IsUnique();

                    b.ToTable("Advisories", (string)null);
                });

            modelBuilder.Entity("Shield.Core.Domain.FeedSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursor")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("Feed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RateLimitResetAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Feed")
                        .IsUnique();

                    b.ToTable("FeedSyncStates", (string)null);
                });

            modelBuilder.Entity("Shield.Core.Domain.PackageMeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ecosystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintainersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TarballSha")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ecosystem", "Name", "Version")
                        .IsUnique();

                    b.ToTable("PackageMetas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
